#version: "3"                           # 파일 규격 버전
#services:                              # 이 항목 밑에 실행하려는 컨테이너 들을 정의
#  redis-server:                        # 서비스명
#    container_name: redis-server       # 컨테이너 명
#    build:
#      dockerfile: Dockerfile
#      context: ./redis
#    image: jiyoung10/redis-server
#  database-mysql:
#    container_name: database-mysql
#    build:
#      dockerfile: Dockerfile
#      context: ./database
#    image: jiyoung10/database-mysql
#    environment:
#      - MYSQLDB_DATABASE=pharmacy-recommendation
#      - MYSQLDB_ROOT_PASSWORD=system
#      - TZ=Asia/Seoul
#    volumes:
#      - ./database/config:/etc/mysql/conf.d
#    command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
#    ports:
#      - "3306:3306"      # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
#  pharmacy-recommendation:
#    container_name: pharmacy-recommendation
#    build: .
#    image: jiyoung10/pharmacy-recommendation
#    environment:
#      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
#      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}